table Targets
	lineageTag: d7dc1c4c-0181-4f23-8eb3-064224282b61

	measure Target = ```
			
				IF(
				HASONEVALUE('Salesperson (Performance)'[Salesperson]),
				SUM(Targets[TargetAmount])
				)
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 026fcd76-6f42-4c6c-a4d5-0d00b8e66ef7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Variance = ```
			
						IF(
							HASONEVALUE('Salesperson (Performance)'[Salesperson]),
							SUM(Sales[Sales]) - [Target]
						)
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ddd575c0-410b-4b2b-8211-2553eb977c08

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Variance Margin' = ```
			
						DIVIDE([Variance], [Target])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 16123f0d-356e-451f-a0da-9d99f96534aa

	column EmployeeID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ebbd7b62-34c8-4f08-bed5-f92ab007b99a
		summarizeBy: none
		sourceColumn: EmployeeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TargetMonth
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 522ac14d-862d-4dd7-b1d5-c272dda2cfb4
		summarizeBy: none
		sourceColumn: TargetMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TargetAmount
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 98b80e07-ebff-4a18-b058-1acd853c4561
		summarizeBy: sum
		sourceColumn: TargetAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Targets = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pResellerSalesTargets),[Delimiter=",", Columns=14, Encoding=1200, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}, {"EmployeeID", Int64.Type}, {"M01", type text}, {"M02", type text}, {"M03", type text}, {"M04", type text}, {"M05", type text}, {"M06", type text}, {"M07", type text}, {"M08", type text}, {"M09", type text}, {"M10", type text}, {"M11", type text}, {"M12", type text}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Year", "EmployeeID"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Other Columns", each ([Value] <> "-")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Attribute", "MonthNumber"}, {"Value", "Target"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","M","",Replacer.ReplaceText,{"MonthNumber"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"MonthNumber", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type1", "TargetMonth", each Text.Combine({Text.From([MonthNumber], "en-US"), "/1/", Text.From([Year], "en-US")}), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Year", "MonthNumber"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"Target", Currency.Type}, {"TargetMonth", type date}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type2", "Multiplication", each [Target] * 1000, Currency.Type),
				    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Multiplication",{"Target"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Multiplication", "TargetAmount"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

